# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_item_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
