# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20170728_2116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Museum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='industry',
            options={'verbose_name_plural': 'Industries'},
        ),
        migrations.RemoveField(
            model_name='college',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='industry',
            name='amount',
        ),
    ]
