# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20170910_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
    ]
