# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_college_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('openingHours', models.CharField(default='00:00', max_length=5)),
                ('closingHours', models.CharField(default='00:00', max_length=5)),
                ('description', models.TextField()),
            ],
        ),
    ]
