# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'test'), ('2', 'test2')], default=1, max_length=200),
        ),
    ]
