# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'Colleges'), ('2', 'Libraries'), ('3', 'Industries'), ('4', 'Hotels'), ('5', 'Parks'), ('6', 'Zoos'), ('7', 'Museums'), ('8', 'Restaurants'), ('9', 'Malls'), ('10', 'Libraries')], default=1, max_length=200),
        ),
    ]
