# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_library_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='closingHours',
        ),
        migrations.RemoveField(
            model_name='college',
            name='description',
        ),
        migrations.RemoveField(
            model_name='college',
            name='openingHours',
        ),
        migrations.AddField(
            model_name='college',
            name='departments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='college',
            name='email',
            field=models.TextField(default=''),
        ),
    ]
