# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-10 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20170729_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=3)),
                ('heading1', models.TextField(default='')),
                ('para1', models.TextField(default='')),
                ('heading2', models.TextField(default='')),
                ('para2', models.TextField(default='')),
            ],
        ),
    ]
