# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-12 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20171009_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='industry',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='library',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='mall',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='museum',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='park',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
        migrations.AddField(
            model_name='zoo',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.City'),
        ),
    ]
