# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.FilePathField(default='', max_length=200),
        ),
    ]
