# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 01:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20171016_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.FilePathField(path='smartcity/smartcity/static/images'),
        ),
    ]
