# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 01:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_auto_20171016_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.FilePathField(path='STATIC_ROOT/images'),
        ),
    ]
