# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_auto_20171016_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.FilePathField(null=True, path='/college/'),
        ),
    ]
