# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20171016_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
