# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-16 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20171017_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(default='C:\\Users\\Maske\\smartcity/smartcity/media_cdn\\college', null=True, upload_to=''),
        ),
    ]
