# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0037_auto_20171017_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.ImageField(null=True, upload_to='cafe/'),
        ),
        migrations.AlterField(
            model_name='college',
            name='image',
            field=models.ImageField(null=True, upload_to='college/'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='industry',
            name='image',
            field=models.ImageField(null=True, upload_to='industry/'),
        ),
        migrations.AlterField(
            model_name='library',
            name='image',
            field=models.ImageField(null=True, upload_to='library/'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='image',
            field=models.ImageField(null=True, upload_to='mall/'),
        ),
        migrations.AlterField(
            model_name='museum',
            name='image',
            field=models.ImageField(null=True, upload_to='museum/'),
        ),
        migrations.AlterField(
            model_name='park',
            name='image',
            field=models.ImageField(null=True, upload_to='hotel/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(null=True, upload_to='restaurant/'),
        ),
        migrations.AlterField(
            model_name='zoo',
            name='image',
            field=models.ImageField(null=True, upload_to='zoo/'),
        ),
    ]
