# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 06:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20170728_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='closingHours',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='openingHours',
            field=models.IntegerField(default=0),
        ),
    ]
