# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-28 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20170728_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
