# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20170729_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
